### ISSUE TITLE
Improved touch button behavior

### ISSUE THREAD

**Issue by keiranlovett** [jbmorley/gameplay#2]
Possibly extend the actual touch boundaries of buttons beyond the physical/graphical representation. With a lack of tactile feedback and a small body its difficult to control buttons such as the direction pad. By extending the hitbox of the buttons a few pixels around the body it can decrease the misses.
![hitbox](https://f.cloud.github.com/assets/544025/152233/a5e04a56-75bb-11e2-88e8-378fe4d0a07c.jpg)

**Comment by jbmorley** [comment]
Fixed in 16780fbc03eaaacf8de84dae2edcb6c2c255d4dc.
