### ISSUE TITLE
Audio performance issues

### ISSUE THREAD

**Issue by jbmorley** [jbmorley/gameplay#26]
Some users have found that audio performance is poor on earlier devices, making games unplayable without muting the device.

We should explore what's can be done about this. Worst-case, we should consider adding an option to allow users to disable audio on these devices.

**Comment by cmilz** [comment]
I would like to have an option to disable the audio for sure ... But ontop of that i would love to be able to play my own audio (running in the background) while playing games

**Comment by jbmorley** [comment]
@cmilz I'm fairly sure that will be possible by allowing you to disable the in-game audio.

**Comment by mendezdavey** [comment]
My iPhone 6plus makes a buzzing sound when I relaunch gameplay color. A way that I get around this is to play a song from my music and then relaunch the app. I get a faint popping sound and then the sound is fixed.

**Comment by jbmorley** [comment]
@mendezdavey Sadly that looks to be a regression in iOS :(.

**Comment by jbmorley** [comment]
@cmilz 13d0fa92b51e62c043332c88d3cb1fa7231687ea adds support for disabling audio.
