### ISSUE TITLE
Support different emulation speeds / fast-forward

### ISSUE THREAD

**Issue by jbmorley** [jbmorley/gameplay#37]

**Comment by mendezdavey** [comment]
The speed at 1.0 is still too fast. Everything seems rushed and the music is too fast to enjoy it. Maybe a .6, .7, or .8 speed might fix it.

**Comment by jbmorley** [comment]
@mendezdavey I think what your seeing might be best characterised as a different issue: that 1x isn't actually running at the correct speed? Is that what you're seeing?
