### ISSUE TITLE
Make it easier to press button combinations

### ISSUE THREAD

**Issue by cmilz** [jbmorley/gameplay#41]
It's not so much as a problem but I am not sure.. Trying to play a certain game which requires A+B+start+select to be pressed to save the game. Would it be possible to add a single button to emulate those 4 buttons? I can get it to work maybe 1 in 10 times.

**Comment by jbmorley** [comment]
I guess you're trying to save in Zelda; that has a key press like that if I remember correctly?

It's certainly very difficult to trigger this at the moment so I agree it should be an issue – thanks for raising it.

As for the fix, I've been trying to avoid game-specific tweaks like this so I'll have a think what we can do to just make it behave the way it's meant to...

**Comment by jbmorley** [comment]
Support for A + B + Start + Select has now been added to release 2.2.1 (see #53).
