### ISSUE TITLE
Resetting

### ISSUE THREAD

**Issue by cmilz** [jbmorley/gameplay#42]
Whenever I leave the app to do other stuff either send a text or enter other apps and try to go back to this app either through the app switcher or just relaunch the app the games tend to reset now it doesn't happen all the time just when I'm off it for approximately 4-5 mins.

it is just a pain if I forget to save before switching.

**Comment by jbmorley** [comment]
Unfortunately this is due to a restriction of iOS: there is no notification of the backgrounding event, so it's not possible to know when to write the emulation state to disk.
