### ISSUE TITLE
Issues with audio-underflow and skipped frames when pressing buttons

### ISSUE THREAD

**Issue by maxxtrarice** [jbmorley/gameplay#52]
There's a bit of lag when playing pokemon. I'm not sure if it just lags or the d-buttons are not responding well. Using iphone 6+ by the way.

**Comment by cmilz** [comment]
Which pokemon? I've played Pokemon Yellow without any problems using iPhone 6.

**Comment by jbmorley** [comment]
We've had a few users saying that performance has been a little degraded on the last couple of releases (presumably related to a slight rework of the touch event model). I'm therefore going to co-opt this issue to cover that performance problem which I believe is primarily an issue of audio-underflow (and subsequent emulator clock adjustment) as a result of interaction with UI.

**Comment by jbmorley** [comment]
@maxxtrarice Thanks for raising this – hopefully we can come up with a good solution.

**Comment by jbmorley** [comment]
I've done a little initial investigation into moving the emulation out into a web worker (see #54). This branch isn't complete at the moment and, while it seems to improve performance of general emulation, is currently limited by the fact that it looks like WebKit / Safari doesn't support running the audio in a web worker. This forces the entire audio buffer under-run adjustment process to be again bounded by the main-thread (and often the remaining buffer length to be out of date), meaning that we gain little-or-no benefits from the move.

@taisel Perhaps you have some thoughts on this issue?

**Comment by taisel** [comment]
Solved this in IodineGBA. Requires using SharedArrayBuffer spec instead, since the latency/overhead of transferrable arrays is too great.

**Comment by jbmorley** [comment]
@taisel Awesome. I thought you might have done ;).

So you run audio in the main thread, but write audio directly into the buffer / query the remaining buffer length in the web worker?

**Comment by jbmorley** [comment]
For future reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer

**Comment by jbmorley** [comment]
@taisel Thanks!

**Comment by taisel** [comment]
Yes, should note that Google Chrome does not support subworkers, so trying to spawn a gpu renderer thread from within the core emulation thread is a gotcha. Ran into that when multi-threading gba emulation (And added fallback hell for it).

**Comment by taisel** [comment]
That is, if you're curious about splitting of graphics from cpu interpretation as well.

**Comment by jbmorley** [comment]
@taisel Intersting. Restricting Game Play Color to iOS and Safari-flavoured WebKit certainly makes for a slightly easier life at the moment. I suspect at some point there'll be a motivation to support Android and Chrome though so it's all good to know.

I was quite pleased with the logical separation that putting the emulation on a web worker achieves. Forces the split very effectively.

_Completely unrelated: I had a play with a quick modification to IodineGBA for running on iOS. Unfortunately it crashes Mobile Safari. I can see this is going to be fun :)._

**Comment by taisel** [comment]
The thing is there's a bunch of middle-layer code that doesn't exist in the original gameboy-online project that I added after when working on IodineGBA. This includes the audio mixer shim and all the relevant worker bits.

Also I've run into that iOS crashing as well, that's JSC giving up for what ever reason, iOS 7 JSC doesn't crash, but iOS 8 and up does.

**Comment by jbmorley** [comment]
@taisel I'm looking forward to picking it up actually – seems much cleaner! I presume iOS is giving up due to OOM, though I've not started digging through crash reports yet. Interestingly it doesn't fail when the development console is attached which makes it a little troublesome to debug.

**Comment by taisel** [comment]
Anyhow, the audio solution previously used for multi-threading is a circular ring buffer provided with a separate scratch array that has the sample count on main thread written to it and the two ring buffer counters provided. Int32 atomics apply on the counters.

**Comment by jbmorley** [comment]
Of course – that makes sense! Sounds a heck of a lot like my day job ;).

**Comment by taisel** [comment]
Just don't attempt furthering of the transferrable array code, that API has too much inherent jank and overhead.

**Comment by taisel** [comment]
Some IodineGBA code in question:
https://github.com/taisel/IodineGBA/blob/master/user_scripts/AudioGlueCode.js
https://github.com/taisel/IodineGBA/blob/master/user_scripts/WorkerGlueCode.js
https://github.com/taisel/IodineGBA/blob/master/IodineGBA/core/Worker.js

**Comment by jbmorley** [comment]
Thank you. I shall have a play and see if I can convince some hybrid solution to work.

**Comment by taisel** [comment]
Yeah.... I tried transferrable array support in gameboy-online years ago, it turned out extremely poorly.

**Comment by taisel** [comment]
Don't worry about the futex stuff, you should not need to touch it. The only usage for that is rendering the graphics separately from the cpu interpretation in a separate thread from it.

**Comment by taisel** [comment]
Sorry for blowing up this thread.

@s3ththompson Multi-threading in WASM I'm assuming relies on the https://github.com/tc39/ecmascript_sharedmem spec for interop with JavaScript. I assume that means how that unstable API can be used here is relevant for feedback for WASM indirectly.

**Comment by jbmorley** [comment]
Worked around for the time being by disabling button animations.

**Comment by s3ththompson** [comment]
Thanks for the heads up @taisel! I'll take a look. Yes, multithreading in WebAssembly will need to interop seamlessly with JS via SharedArrayBuffers.
